#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "${ROOT_DIR}"

IMAGE=${FFTM_CLEANUP_CONTAINER_IMAGE:-${FFTM_CONTAINER_IMAGE:-/scratch/evstigneevnm/fftm/fftm_bench_a100.sqsh}}
DATA_DIR=${FFTM_CLEANUP_DATA_DIR:-${FFTM_DATA_DIR:-/scratch/evstigneevnm/fftm/data_cleanup_prod_guard_$(date +%Y%m%d_%H%M%S)}}
GPU_COUNTS=${FFTM_CLEANUP_GPU_COUNTS:-6,7,8}
SRUN_EXTRA_ARGS=${FFTM_CLEANUP_SRUN_EXTRA_ARGS:---exclude=cn13}
RUN_QUIET_SMOKE=${FFTM_CLEANUP_RUN_QUIET_SMOKE:-1}
DRY_RUN=${FFTM_CLEANUP_DRY_RUN:-0}
IFS=',' read -r -a GPU_COUNT_ITEMS <<< "${GPU_COUNTS}"
EXPECTED_CASES=$(( 2 * ${#GPU_COUNT_ITEMS[@]} ))

printf 'FFTM cleanup production guard\n'
printf '  image=%s\n' "${IMAGE}"
printf '  output=%s\n' "${DATA_DIR}"
printf '  GPUs=%s; expected cases=%d (3D 2048^3 and 4D 320^4)\n' "${GPU_COUNTS}" "${EXPECTED_CASES}"

if [[ "${RUN_QUIET_SMOKE}" == "1" ]]; then
    mkdir -p "${DATA_DIR}"
    SRUN_EXTRA_ITEMS=()
    if [[ -n "${SRUN_EXTRA_ARGS}" ]]; then
        read -r -a SRUN_EXTRA_ITEMS <<< "${SRUN_EXTRA_ARGS}"
    fi
    QUIET_SMOKE_CMD=(
        srun
        "${SRUN_EXTRA_ITEMS[@]}"
        -N 1
        -n 1
        -G 1
        --ntasks-per-node=1
        --gpus-per-node=1
        --kill-on-bad-exit=1
        --time=00:05:00
        --container-image "${IMAGE}"
        --container-workdir /opt/fftm/bin
        --container-entrypoint /opt/fftm/bin/test_fftm_quiet_default.bin
    )
    printf 'Running default-options quiet smoke: '
    printf '%q ' "${QUIET_SMOKE_CMD[@]}"
    printf '\n'
    if [[ "${DRY_RUN}" != "1" ]]; then
        "${QUIET_SMOKE_CMD[@]}" 2>&1 | tee "${DATA_DIR}/quiet_default.log"
    fi
fi

FFTM_CONTAINER_IMAGE="${IMAGE}" \
FFTM_DATA_DIR="${DATA_DIR}" \
FFTM_NODE_COUNTS=1 \
FFTM_GPU_COUNTS="${GPU_COUNTS}" \
FFTM_GPUS_PER_NODE=8 \
FFTM_DEVICE_MEMORY_MIB=81920 \
FFTM_BENCHMARK_SIZES_3D=none \
FFTM_BENCHMARK_SIZES_4D=none \
FFTM_FIXED_SCALING_SIZES_3D=2048 \
FFTM_FIXED_SCALING_SIZES_4D=320 \
FFTM_EXTRA_SIZES_3D= \
FFTM_EXTRA_SIZES_3D_BY_GPU= \
FFTM_TRANSPORTS=cuda_aware \
FFTM_MODES=p2p-waitany \
FFTM_STRATEGIES_3D=pencil-pencil \
FFTM_STRATEGIES_4D=slab-slab \
FFTM_SKIP_FFTS=1 \
FFTM_SKIP_FFTM=0 \
FFTM_INCLUDE_VERSIONED=0 \
FFTM_3D_BACKENDS=native \
FFTM_PENCIL_PIPELINES=reference-parity \
FFTM_PENCIL_LAYOUTS=auto \
FFTM_PENCIL_PENCIL_GRID_ORIENTATIONS=production \
FFTM_P2P_VARIANTS=byte-packed \
FFTM_P2P_SCHEDULERS=main \
FFTM_LARGE_COUNT_P2P_TRANSPORTS=hindexed \
FFTM_USE_DIRECT_BACKWARD_RECEIVE=0 \
FFTM_DIRECT_P2P_CUDA_AWARE=1 \
FFTM_USE_P2P_SEND_THREAD=0 \
FFTM_USE_P2P_BYTE_TRANSFER=1 \
FFTM_USE_PERSISTENT_P2P=0 \
FFTM_USE_READY_P2P_SEND=0 \
FFTM_USE_3D_DEFERRED_SEND_COMPLETION=0 \
FFTM_USE_NATIVE_OPT0_DEFAULT_Z_LAYOUT=1 \
FFTM_USE_NATIVE_OPT0_REFERENCE_Y_BUFFER_TOPOLOGY=1 \
FFTM_USE_NATIVE_OPT0_TIGHT_Y_PLAN_SEQUENCE=1 \
FFTM_USE_NATIVE_OPT0_SHARED_Y_PLAN_HANDLES=1 \
FFTM_USE_NATIVE_OPT0_Y_GROUP_DEVICE_SYNC=1 \
FFTM_USE_NATIVE_OPT0_Y_NO_SYNC_EXEC=1 \
FFTM_USE_NATIVE_OPT0_RAW_Y_PLAN_ARRAY_EXECUTOR=1 \
FFTM_ALLOW_NATIVE_OPT0_DIAGNOSTIC_VARIANTS=0 \
FFTM_USE_FFT_EXEC_NO_SYNC=0 \
FFTM_4D_SLAB_XW_TRANSPOSES=native \
FFTM_4D_SLAB_XW_BATCHED_PEER_KERNELS=off \
FFTM_4D_SLAB_XW_KERNEL_LAYOUTS=buffer-contiguous \
FFTM_4D_SLAB_XW_VECTOR4_KERNELS=off \
FFTM_4D_SLAB_XW_TILED_KERNELS=off \
FFTM_4D_SLAB_XW_LAYOUT_STAGES=off \
FFTM_4D_SLAB_XW_NATIVE_SPECTRAL_LAYOUTS=native \
FFTM_4D_NATIVE_XW_DIRECT_LAYOUTS=on \
FFTM_4D_NATIVE_XW_PROTOCOLS=chunked \
FFTM_4D_NATIVE_XW_CHUNK_MIB=512 \
FFTM_4D_NATIVE_XW_CHUNK_WINDOWS=1 \
FFTM_4D_NATIVE_XW_COMPACT_STAGINGS=on \
FFTM_4D_SLAB_NATIVE_WORK_AREA_ALIASES=on \
FFTM_4D_SLAB_NATIVE_WZ_COMM_LAYOUTS=on \
FFTM_4D_SLAB_NATIVE_WZ_PLAN_CONCURRENCIES=4 \
FFTM_4D_SLAB_NATIVE_WZ_READY_PIPELINES=on \
FFTM_PRINT_PENCIL_SCHEDULE=0 \
FFTM_ENABLE_NATIVE_STAGE_TIMERS=0 \
FFTM_ENABLE_LOCAL_FFT_DIAGNOSTICS=0 \
FFTM_ENABLE_GPU_TELEMETRY=1 \
FFTM_BENCHMARK_TIMES=${FFTM_CLEANUP_BENCHMARK_TIMES:-10} \
FFTM_WARMUP=${FFTM_CLEANUP_WARMUP:-3} \
FFTM_RUN_PREFLIGHT=${FFTM_CLEANUP_RUN_PREFLIGHT:-1} \
FFTM_SRUN_EXTRA_ARGS="${SRUN_EXTRA_ARGS}" \
FFTM_SRUN_TIME=${FFTM_CLEANUP_SRUN_TIME:-00:45:00} \
FFTM_TIMEOUT_SECONDS=${FFTM_CLEANUP_TIMEOUT_SECONDS:-2700} \
FFTM_STOP_ON_FAILURE=1 \
FFTM_DRY_RUN="${DRY_RUN}" \
scripts/run_slurm_pyxis_benchmarks.sh
